# TBD: update yml build step for OfarWeb
# ASP.NET Core template YML file
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'nuget restore' 
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  continueOnError: true
  enabled: true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
