# Starter empty pipeline
# See: https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo TBD: build steps for building the app
  displayName: 'TBD: real build steps to be made'
